name: manually triggerable CI workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: my arg
        default: world
        required: true

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, ${github.event.inputs.name}!"
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

